# Atividade 2

**Membros:**

*   Giulia Monteiro Garrido (RA: 24010281)
*   Thomaz Dacorso (RA: 24012310)
*   Victor França (RA: 24010801)
*   Vitor Furuta (RA: 24008775)

### Particionamento dos dados brutos

In [11]:
import scipy as sp
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pandas as pd
import numpy as np
import os
import plotly.graph_objects as go

In [12]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("aliiihussain/amazon-sales-dataset")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\thomd\.cache\kagglehub\datasets\aliiihussain\amazon-sales-dataset\versions\1

In [13]:
name_files = os.listdir(path)
new_path = path+"/"+name_files[0]
csv_file = open(new_path)
df = pd.read_csv(csv_file)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          50000 non-null  int64
 1   order_date        50000 non-null  str
 2   product_id        50000 non-null  int64
 3   product_category  50000 non-null  str
 4   price             50000 non-null  float64
 5   discount_percent  50000 non-null  int64
 6   quantity_sold     50000 non-null  int64
 7   customer_region   50000 non-null  str
 8   payment_method    50000 non-null  str
 9   rating            50000 non-null  float64
 10  review_count      50000 non-null  int64
 11  discounted_price  50000 non-null  float64
 12  total_revenue     50000 non-null  float64
dtypes: float64(4), int64(5), str(4)
memory usage: 5.0 MB

In [15]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [16]:
df.groupby(df['order_date'].dt.year).size()

order_date
2022    24926
2023    25074
dtype: int64

In [17]:
df.groupby(df['order_date'].dt.to_period('M')).size().reset_index(name='count').rename(columns={'order_date': 'year_month'})

   year_month  count
0     2022-01   2151
1     2022-02   1899
2     2022-03   2155
3     2022-04   2089
4     2022-05   2073
5     2022-06   2044
6     2022-07   2093
7     2022-08   2189
8     2022-09   2100
9     2022-10   2060
10    2022-11   2000
11    2022-12   2073
12    2023-01   2187
13    2023-02   1867
14    2023-03   2098
15    2023-04   1997
16    2023-05   2154
17    2023-06   2132
18    2023-07   2216
19    2023-08   2162
20    2023-09   2033
21    2023-10   2159
22    2023-11   2006
23    2023-12   2063

In [18]:
df_2022=df[df["order_date"].dt.year == 2022]

In [19]:
df_2022

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
0,1,2022-04-13,2637,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52
2,3,2022-09-28,3670,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28
3,4,2022-04-17,2522,Books,371.95,15,4,Middle East,UPI,5.0,212,316.16,1264.64
4,5,2022-03-13,1717,Beauty,201.68,0,4,Middle East,UPI,4.6,308,201.68,806.72
6,7,2022-01-21,4068,Books,15.78,0,5,Asia,UPI,1.6,415,15.78,78.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49992,49993,2022-12-30,4078,Fashion,33.20,0,5,Middle East,Cash on Delivery,2.5,357,33.20,166.00
49993,49994,2022-09-04,3615,Sports,306.98,15,2,North America,Wallet,4.8,438,260.93,521.86
49995,49996,2022-09-03,1433,Beauty,26.99,0,5,Middle East,Credit Card,2.4,386,26.99,134.95
49996,49997,2022-07-03,1428,Beauty,294.23,10,5,Asia,Credit Card,3.1,8,264.81,1324.05
49998,49999,2022-09-30,4371,Beauty,307.54,5,1,Middle East,UPI,1.8,316,292.16,292.16

In [27]:
years = []
for i in df["order_date"]:
    if i.year not in years:
        years.append(i.year)

years.sort()
print(years)

[2022, 2023]

In [28]:
months = []
for i in df["order_date"]:
    if i.month not in months:
        months.append(i.month)
months.sort()
print(months)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [ ]:
os.makedirs("data", exist_ok=True)

for year in years:
    folder_path_year = f"data/{year}"
    os.makedirs(folder_path_year, exist_ok=True)
    for month in months:
        folder_path_month = f"{folder_path_year}/{month}"
        os.makedirs(folder_path_month, exist_ok=True)
        df_month = df[(df["order_date"].dt.year == year) & (df["order_date"].dt.month == month)]
        with open(f"{folder_path_month}/data.csv", "w") as f:
            (df_month.to_csv(f, index=False))

TypeError: write() argument must be str, not None